name: Build Jar 
# OR, publish per each commit
on:
  push:
    branches: [ master, develop ]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions: write-all 
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:  
          java-version: '21'  
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build Jar 
        run: | 
          ./gradlew build 
          mkdir -p ${{ github.workspace }}/artifacts 
          mv target/*.jar ${{ github.workspace }}/artifacts/ 

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
            name: my-artifact # NOTE: same artifact name
            path: ${{ github.workspace }}/artifacts/ 
